"""update table parent

Revision ID: 2ad27326dc78
Revises: e4a965ca531d
Create Date: 2025-08-21 16:34:14.506903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad27326dc78'
down_revision: Union[str, Sequence[str], None] = 'e4a965ca531d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('parent_admission_no_key'), 'parent', type_='unique')
    op.drop_column('parent', 'admission_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('admission_no', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('parent_admission_no_key'), 'parent', ['admission_no'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
